platform :ios, '8.0'
target 'BostonTour' do
pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
pod 'GoogleMaps'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

end